/*
UNIVERSIDAD ESTATAL A DISTANCIA
VICERRECTORIA ACADÉMICA
ESCUELA DE CIENCIAS EXACTAS Y NATURALES
CARRERA DE INGENIERÍA INFORMÁTICA

PROYECTO EVALUATIVO
LISTAS ENLAZADAS

GRUPO 03
PROFESORA MIRIAM MORA MORALES

DAYRON ANTONY CHAVES SANDOVAL
305240018

CENTRO UNIVERSITARIO DE TURRIALBA

FECHA DE ENTREGA
25 DE ABRIL DEL 2021

PRIMER CUATRIMESTRE, 2021.
*/

package Estadia;

import ListaEnlazadaOrdenada.Nodo;

public class Estadia 
{
    public String nombre;
    
    public int dias;
    
    public int monto;
   
}
